name = "selftunnel-signaling"
main = "src/index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "SELFTUNNEL_KV", id = "e0d3d5cbd5d6447488a2dbcf2f5fd083" }
]

[durable_objects]
bindings = [
  { name = "NETWORK_STORE", class_name = "NetworkStore" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NetworkStore"]

[triggers]
crons = []
